export const Links = {
    backpackLinks: {
        backpackTauntPrompt : [
            "https://backpack.tf/stats/Unique/Taunt%3A%20Burstchester/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Victory%20Lap/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Yeti%20Smash/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Kazotsky%20Kick/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Second%20Rate%20Sorcery/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Mannrobics/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Schadenfreude/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Zoomin%27%20Broom/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Balloonibouncer/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Yeti%20Punch/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Scaredy-cat%21/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Conga/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Fist%20Bump/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Bunnyhopper/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Bucking%20Bronco/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Russian%20Rubdown/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Texas%20Twirl%20%27Em/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Boston%20Breakdance/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Time%20Out%20Therapy/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Drunk%20Mann%27s%20Cannon/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Rock%2C%20Paper%2C%20Scissors/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Killer%20Solo/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Shanty%20Shipmate/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Pooped%20Deck/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Doctor%27s%20Defibrillators/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Killer%20Joke/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Carlton/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Pool%20Party/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Head%20Doctor/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Mannbulance%21/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Skating%20Scorcher/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Panzer%20Pants/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Shooter%27s%20Stakeout/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Star-Spangled%20Strategy/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Dueling%20Banjo/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Jumping%20Jack/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Road%20Rager/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Strange%20Cosmetic%20Part%3A%20Freezecam%20Taunt%20Appearances/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Rancho%20Relaxo/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20Roasty%20Toasty/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Drunken%20Sailor/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Homerunner%27s%20Hobby/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Russian%20Arms%20Race/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Scooty%20Scoot/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Taunt%3A%20The%20Table%20Tantrum/Tradable/Craftable",
        ],
        backpackCurrencyPrompt : [
            "https://backpack.tf/stats/Unique/Mann%20Co.%20Supply%20Crate%20Key/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Tour%20of%20Duty%20Ticket/Tradable/Non-Craftable",
            "https://backpack.tf/stats/Unique/Tour%20of%20Duty%20Ticket/Tradable/Craftable",
            "https://backpack.tf/stats/Unique/Earbuds/Tradable/Craftable",
        ],
    },
    scrapLinks : {
        scrapTauntPrompt : "https://scrap.tf/buy/items",
        scrapWeaponPrompt : "https://scrap.tf/buy/weapons",
    }
}
